export enum Icon {
  TUNE_ON = "TUNE_ON",
  TUNE_ON_OVER = "TUNE_ON_OVER",
  TUNE_ON_DOWN = "TUNE_ON_DOWN",
  TUNE_OFF = "TUNE_OFF",
  TUNE_OFF_OVER = "TUNE_OFF_OVER",
  TUNE_OFF_DOWN = "TUNE_OFF_DOWN",

  FINGERING_ON = "FINGERING_ON",
  FINGERING_ON_OVER = "FINGERING_ON_OVER",
  FINGERING_ON_DOWN = "FINGERING_ON_DOWN",
  FINGERING_OFF = "FINGERING_OFF",
  FINGERING_OFF_OVER = "FINGERING_OFF_OVER",
  FINGERING_OFF_DOWN = "FINGERING_OFF_DOWN",

  STATS = "STATS",
  STATS_OVER = "STATS_OVER",
  STATS_DOWN = "STATS_DOWN",
  STATS_SELECTED = "STATS_SELECTED",

  ADD = "ADD",
  ADD_OVER = "ADD_OVER",
  ADD_DOWN = "ADD_DOWN",
  ADD_SELECTED = "ADD_SELECTED",

  DOWNLOAD = "DOWNLOAD",
  DOWNLOAD_OVER = "DOWNLOAD_OVER",
  DOWNLOAD_DOWN = "DOWNLOAD_DOWN",

  TEXT = "TEXT",
  TEXT_OVER = "TEXT_OVER",
  TEXT_DOWN = "TEXT_DOWN",
  TEXT_SELECTED = "TEXT_SELECTED",

  LIST = "LIST",
  LIST_OVER = "LIST_OVER",
  LIST_DOWN = "LIST_DOWN",
  LIST_SELECTED = "LIST_SELECTED",

  INFO = "INFO",
  INFO_OVER = "INFO_OVER",
  INFO_DOWN = "INFO_DOWN",
  INFO_SELECTED = "INFO_SELECTED",

  SETTINGS_ON = "SETTINGS_ON",
  SETTINGS_ON_OVER = "SETTINGS_ON_OVER",
  SETTINGS_ON_DOWN = "SETTINGS_ON_DOWN",
  SETTINGS_OFF = "SETTINGS_OFF",
  SETTINGS_OFF_OVER = "SETTINGS_OFF_OVER",
  SETTINGS_OFF_DOWN = "SETTINGS_OFF_DOWN",
  SETTINGS_ON_SELECTED = "SETTINGS_ON_SELECTED",
  SETTINGS_OFF_SELECTED = "SETTINGS_OFF_SELECTED",

  FULLSCREEN_ON = "FULLSCREEN_ON",
  FULLSCREEN_ON_OVER = "FULLSCREEN_ON_OVER",
  FULLSCREEN_ON_DOWN = "FULLSCREEN_ON_DOWN",
  FULLSCREEN_OFF = "FULLSCREEN_OFF",
  FULLSCREEN_OFF_OVER = "FULLSCREEN_OFF_OVER",
  FULLSCREEN_OFF_DOWN = "FULLSCREEN_OFF_DOWN",

  HOME = "HOME",
  HOME_OVER = "HOME_OVER",
  HOME_DOWN = "HOME_DOWN",

  SAVE_ON = "SAVE_ON",
  SAVE_ON_OVER = "SAVE_ON_OVER",
  SAVE_ON_DOWN = "SAVE_ON_DOWN",
  SAVE_OFF = "SAVE_OFF",
  SAVE_OFF_OVER = "SAVE_OFF_OVER",
  SAVE_OFF_DOWN = "SAVE_OFF_DOWN",

  USER_ON_SELECTED = "USER_ON_SELECTED",
  USER_OFF_SELECTED = "USER_OFF_SELECTED",
  USER_ON = "USER_ON",
  USER_ON_OVER = "USER_ON_OVER",
  USER_ON_DOWN = "USER_ON_DOWN",
  USER_OFF = "USER_OFF",
  USER_OFF_OVER = "USER_OFF_OVER",
  USER_OFF_DOWN = "USER_OFF_DOWN",

  //LEVELS

  A = "A",
  A_OVER = "A_OVER",
  A_DOWN = "A_DOWN",
  A_SELECTED = "A_SELECTED",

  B = "B",
  B_OVER = "B_OVER",
  B_DOWN = "B_DOWN",
  B_SELECTED = "B_SELECTED",

  C = "C",
  C_OVER = "C_OVER",
  C_DOWN = "C_DOWN",
  C_SELECTED = "C_SELECTED",

  D = "D",
  D_OVER = "D_OVER",
  D_DOWN = "D_DOWN",
  D_SELECTED = "D_SELECTED",

  E = "E",
  E_OVER = "E_OVER",
  E_DOWN = "E_DOWN",
  E_SELECTED = "E_SELECTED",

  F = "F",
  F_OVER = "F_OVER",
  F_DOWN = "F_DOWN",
  F_SELECTED = "F_SELECTED",

  G = "G",
  G_OVER = "G_OVER",
  G_DOWN = "G_DOWN",
  G_SELECTED = "G_SELECTED",

  PRIVATE = "PRIVATE",
  PRIVATE_OVER = "PRIVATE_OVER",
  PRIVATE_DOWN = "PRIVATE_DOWN",
  PRIVATE_SELECTED = "PRIVATE_SELECTED",
}
