export enum RightHandLayout {
  C_GRIFF_EUROPE = "C_GRIFF_EUROPE",
  C_GRIFF_2 = "C_GRIFF_2",
  B_GRIFF_BAJAN = "B_GRIFF_BAJAN",
  C_GRIFF_FINN = "C_GRIFF_FINN",
  D_GRIFF_1 = "D_GRIFF_1",
  D_GRIFF_2 = "D_GRIFF_2",
  PIANO_RIGHT_HAND = "PIANO_RIGHT_HAND",
}
